# Generated by Django 4.0.4 on 2022-04-12 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('OFAddress', models.CharField(max_length=180, primary_key=True, serialize=False)),
                ('AirportCode', models.CharField(max_length=180, unique=True)),
                ('Phone', models.IntegerField()),
                ('Name', models.CharField(max_length=180)),
                ('Email_Addr', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('WID', models.IntegerField(primary_key=True, serialize=False)),
                ('specialization', models.CharField(max_length=180)),
                ('HAddress', models.CharField(max_length=180)),
                ('Hname', models.CharField(max_length=180)),
                ('Hsex', models.CharField(max_length=180)),
                ('HBriDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Insurence_Company',
            fields=[
                ('IID', models.IntegerField(primary_key=True, serialize=False)),
                ('IAddr', models.CharField(max_length=180)),
                ('IName', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='Medical_Exam',
            fields=[
                ('Exam_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Eye', models.CharField(blank=True, max_length=180, null=True, unique=True)),
                ('Scan', models.CharField(blank=True, max_length=180, null=True, unique=True)),
                ('Blood', models.CharField(blank=True, max_length=180, null=True, unique=True)),
                ('AppDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Medical_Facility',
            fields=[
                ('MFAddress', models.CharField(max_length=180, primary_key=True, serialize=False)),
                ('Phone', models.IntegerField()),
                ('Name', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('HID', models.IntegerField(primary_key=True, serialize=False)),
                ('Age', models.IntegerField()),
                ('Name', models.CharField(max_length=180)),
                ('Sex', models.CharField(max_length=180)),
                ('Birth_date', models.DateTimeField()),
                ('IID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myproject_api.insurence_company')),
                ('WID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myproject_api.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Health_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HisDiag', models.CharField(max_length=180)),
                ('VacRec', models.CharField(max_length=180)),
                ('ExamRec', models.CharField(max_length=180)),
                ('Exam_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myproject_api.medical_exam')),
                ('HID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject_api.patient', unique=True)),
                ('OFAddress', models.ManyToManyField(blank=True, null=True, to='myproject_api.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('NurID', models.IntegerField(primary_key=True, serialize=False)),
                ('HAddress', models.CharField(max_length=180)),
                ('Hname', models.CharField(max_length=180)),
                ('Hsex', models.CharField(max_length=180)),
                ('HBriDate', models.DateTimeField()),
                ('HID', models.ManyToManyField(blank=True, null=True, to='myproject_api.patient_health_history')),
                ('MFAddress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myproject_api.medical_facility')),
            ],
        ),
        migrations.AddField(
            model_name='medical_exam',
            name='HID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myproject_api.patient'),
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('LFAddress', models.CharField(max_length=180, primary_key=True, serialize=False)),
                ('LabNo', models.IntegerField(max_length=180, unique=True)),
                ('Phone', models.IntegerField()),
                ('Name', models.CharField(max_length=180)),
                ('Exam_id', models.ManyToManyField(blank=True, null=True, to='myproject_api.medical_exam')),
            ],
        ),
        migrations.AddField(
            model_name='insurence_company',
            name='MFAddress',
            field=models.ManyToManyField(blank=True, null=True, to='myproject_api.medical_facility'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='HID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myproject_api.patient_health_history'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='MFAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myproject_api.medical_facility'),
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Temp', models.IntegerField()),
                ('Disease', models.CharField(max_length=180)),
                ('Medication', models.CharField(max_length=180)),
                ('HID', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='myproject_api.patient')),
                ('WID', models.ManyToManyField(to='myproject_api.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('License_Plate', models.CharField(max_length=180, primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=180)),
                ('HID', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myproject_api.patient')),
                ('MFAddress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myproject_api.medical_facility')),
            ],
        ),
    ]
